name: Upload TTL to LINDAS

on:
  workflow_dispatch:
  push:
    paths:
      - "lindas/test-upload.ttl"

jobs:
  upload-ttl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload TTL to LINDAS
        env:
          LINDAS_USERNAME: ${{ secrets.LINDAS_USERNAME }}
          LINDAS_PASSWORD: ${{ secrets.LINDAS_PW }}
          GRAPH_URI: "https://lindas.admin.ch/fsvo/govtech26-tierseuchen-screener"
        run: |
          curl -v \
            -u "$LINDAS_USERNAME:$LINDAS_PW" \
            -X POST \
            -H "Content-Type: text/turtle" \
            --data-binary @lindas/test-upload.ttl \
            "https://int.graphdb.lindas.admin.ch/repositories/lindas/rdf-graphs/service?graph=$GRAPH_URI"